In [1]:
import pandas as pd
import torch
from torch import nn
from torch import optim

In [15]:
a = torch.ones((3,3)) # create an abitrary tensor

In [16]:
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [17]:
a.size() # get it's shape

torch.Size([3, 3])

In [18]:
b = a.view((1,9)) # change it's shape (contigous mode)

In [19]:
b

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
a.add_(3)

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])

In [21]:
b

tensor([[4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [22]:
c = a.view((1,9)).clone()

In [23]:
c

tensor([[4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [24]:
a.mul_(10)

tensor([[40., 40., 40.],
        [40., 40., 40.],
        [40., 40., 40.]])

In [25]:
c

tensor([[4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [26]:
b

tensor([[40., 40., 40., 40., 40., 40., 40., 40., 40.]])

In [27]:
a.mul(1000)

tensor([[40000., 40000., 40000.],
        [40000., 40000., 40000.],
        [40000., 40000., 40000.]])

In [28]:
a

tensor([[40., 40., 40.],
        [40., 40., 40.],
        [40., 40., 40.]])

In [32]:
d = a.view((1,-1)).clone().detach() # do this

In [34]:
_d = torch.tensor(a.view(1, -1)) # dont do this

/tmp/ipykernel_3745/371725005.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  _d = torch.tensor(a.view(1, -1))


In [37]:
d.type()

'torch.FloatTensor'

In [39]:
d.float()

tensor([[40., 40., 40., 40., 40., 40., 40., 40., 40.]])

In [40]:
d.numpy()

array([[40., 40., 40., 40., 40., 40., 40., 40., 40.]], dtype=float32)

In [41]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [42]:
print(f"Using {device} device.")

Using cpu device.


In [44]:
e = d.to(device)

In [46]:
f = e.cpu().numpy()

In [49]:
e.requires_grad

False

In [50]:
e.requires_grad = True

In [51]:
e

tensor([[40., 40., 40., 40., 40., 40., 40., 40., 40.]], requires_grad=True)

In [52]:
d.requires_grad_()

tensor([[40., 40., 40., 40., 40., 40., 40., 40., 40.]], requires_grad=True)

In [53]:
d

tensor([[40., 40., 40., 40., 40., 40., 40., 40., 40.]], requires_grad=True)