In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import pandas as pd

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [3]:
print(device)

cuda


In [4]:
data = pd.read_csv("https://raw.githubusercontent.com/hsiav2000/simple-regression/master/Salary_Data.csv")

In [5]:
data.corr()

YearsExperience    Salary
YearsExperience         1.000000  0.978242
Salary                  0.978242  1.000000

In [6]:
X = torch.tensor(data.YearsExperience).float().view((30,1)).to(device)
y = torch.tensor(data.Salary).float().view((30,1)).to(device)

In [7]:
X

tensor([[ 1.1000],
        [ 1.3000],
        [ 1.5000],
        [ 2.0000],
        [ 2.2000],
        [ 2.9000],
        [ 3.0000],
        [ 3.2000],
        [ 3.2000],
        [ 3.7000],
        [ 3.9000],
        [ 4.0000],
        [ 4.0000],
        [ 4.1000],
        [ 4.5000],
        [ 4.9000],
        [ 5.1000],
        [ 5.3000],
        [ 5.9000],
        [ 6.0000],
        [ 6.8000],
        [ 7.1000],
        [ 7.9000],
        [ 8.2000],
        [ 8.7000],
        [ 9.0000],
        [ 9.5000],
        [ 9.6000],
        [10.3000],
        [10.5000]], device='cuda:0')

In [8]:
y

tensor([[ 39343.],
        [ 46205.],
        [ 37731.],
        [ 43525.],
        [ 39891.],
        [ 56642.],
        [ 60150.],
        [ 54445.],
        [ 64445.],
        [ 57189.],
        [ 63218.],
        [ 55794.],
        [ 56957.],
        [ 57081.],
        [ 61111.],
        [ 67938.],
        [ 66029.],
        [ 83088.],
        [ 81363.],
        [ 93940.],
        [ 91738.],
        [ 98273.],
        [101302.],
        [113812.],
        [109431.],
        [105582.],
        [116969.],
        [112635.],
        [122391.],
        [121872.]], device='cuda:0')

In [9]:
class LinearRegression(nn.Module):
    def __init__(self, input_size, output_size):
        super().__init__()
        self.linear = nn.Linear(input_size, output_size)
        
    def forward(self, x):
        pred = self.linear(x)
        return pred

In [10]:
model = LinearRegression(1, 1).to(device)

In [11]:
list(model.parameters())

[Parameter containing:
 tensor([[0.7502]], device='cuda:0', requires_grad=True),
 Parameter containing:
 tensor([-0.8106], device='cuda:0', requires_grad=True)]

In [12]:
y_hat = model(X.float().view(-1,1))

In [13]:
model.state_dict()

OrderedDict([('linear.weight', tensor([[0.7502]], device='cuda:0')),
             ('linear.bias', tensor([-0.8106], device='cuda:0'))])

In [14]:
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [15]:
loss_fn  = nn.MSELoss()

In [23]:
n_epochs = 1000

In [24]:
for epoch in range(n_epochs):
    model.train()

    y_hat = model(X)
    loss = loss_fn(y_hat, y)

    print(loss)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

tensor(1.1898e+08, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(1.1824e+08, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(1.1751e+08, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(1.1678e+08, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(1.1606e+08, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(1.1534e+08, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(1.1463e+08, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(1.1393e+08, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(1.1323e+08, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(1.1254e+08, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(1.1185e+08, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(1.1117e+08, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(1.1050e+08, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(1.0983e+08, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(1.0917e+08, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor(1.0851e+08, device='cuda:0', grad

In [25]:
model.state_dict()

OrderedDict([('linear.weight', tensor([[9493.0527]], device='cuda:0')),
             ('linear.bias', tensor([25501.8281], device='cuda:0'))])

In [26]:
list(zip(model(X).squeeze(), y.squeeze()))

[(tensor(35944.1875, device='cuda:0', grad_fn=<UnbindBackward0>),
  tensor(39343., device='cuda:0')),
 (tensor(37842.7969, device='cuda:0', grad_fn=<UnbindBackward0>),
  tensor(46205., device='cuda:0')),
 (tensor(39741.4062, device='cuda:0', grad_fn=<UnbindBackward0>),
  tensor(37731., device='cuda:0')),
 (tensor(44487.9336, device='cuda:0', grad_fn=<UnbindBackward0>),
  tensor(43525., device='cuda:0')),
 (tensor(46386.5430, device='cuda:0', grad_fn=<UnbindBackward0>),
  tensor(39891., device='cuda:0')),
 (tensor(53031.6836, device='cuda:0', grad_fn=<UnbindBackward0>),
  tensor(56642., device='cuda:0')),
 (tensor(53980.9844, device='cuda:0', grad_fn=<UnbindBackward0>),
  tensor(60150., device='cuda:0')),
 (tensor(55879.5977, device='cuda:0', grad_fn=<UnbindBackward0>),
  tensor(54445., device='cuda:0')),
 (tensor(55879.5977, device='cuda:0', grad_fn=<UnbindBackward0>),
  tensor(64445., device='cuda:0')),
 (tensor(60626.1250, device='cuda:0', grad_fn=<UnbindBackward0>),
  tensor(57189.,