In [1]:
import torch
from torch import nn
from torch import optim

In [2]:
a = torch.ones((3,3)) # create an abitrary tensor

In [3]:
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
a.size() # get it's shape

torch.Size([3, 3])

In [5]:
b = a.view((1,9)) # change it's shape (contigous mode)

In [6]:
b

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
a.add_(3)

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])

In [8]:
b

tensor([[4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [9]:
c = a.view((1,9)).clone()

In [10]:
c

tensor([[4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [11]:
a.mul_(10)

tensor([[40., 40., 40.],
        [40., 40., 40.],
        [40., 40., 40.]])

In [12]:
c

tensor([[4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [13]:
b

tensor([[40., 40., 40., 40., 40., 40., 40., 40., 40.]])

In [14]:
a.mul(1000)

tensor([[40000., 40000., 40000.],
        [40000., 40000., 40000.],
        [40000., 40000., 40000.]])

In [15]:
a

tensor([[40., 40., 40.],
        [40., 40., 40.],
        [40., 40., 40.]])

In [16]:
d = a.view((1,-1)).clone().detach() # do this

In [17]:
_d = torch.tensor(a.view(1, -1)) # dont do this

C:\Users\willk\AppData\Local\Temp\ipykernel_9984\3922120528.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  _d = torch.tensor(a.view(1, -1)) # dont do this


In [18]:
d.type()

'torch.FloatTensor'

In [19]:
d.float()

tensor([[40., 40., 40., 40., 40., 40., 40., 40., 40.]])

In [20]:
d.numpy()

array([[40., 40., 40., 40., 40., 40., 40., 40., 40.]], dtype=float32)

In [21]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [22]:
print(f"Using {device} device.")

Using cuda device.


In [23]:
e = d.to(device)

In [24]:
f = e.cpu().numpy()

In [25]:
e.requires_grad

False

In [26]:
e.requires_grad = True

In [27]:
e

tensor([[40., 40., 40., 40., 40., 40., 40., 40., 40.]], device='cuda:0',
       requires_grad=True)

In [28]:
d.requires_grad_()

tensor([[40., 40., 40., 40., 40., 40., 40., 40., 40.]], requires_grad=True)

In [29]:
d

tensor([[40., 40., 40., 40., 40., 40., 40., 40., 40.]], requires_grad=True)